-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "yearReleased" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
